### <center> ASSIGNMENT

1. 
A database is an organized collection of data, so that it can be easily accessed and managed. Data is organized into tables, rows, columns, and index inside databases to make it easier to find relevant information.  
SQL is the programming language used to interface with relational databases. Relational databases model data as records in rows and tables with logical links between them. NoSQL is a class of DBMs that are non-relational and generally do not use SQL. Differences between SQL and NoSQL databases are-

| SQL | NoSQL |
| --- | --- |
| Relational database management system. | Distributed database management system. |
| Veretically scalable. | Horizontally scalable. |
| Fixed or predefined schema. | Dynamic schema. |
| Not suitable for hierarchial data storage. | Best suitable for hierarchical data storage. |
| Best suitable for complex queries. | Not good for complex queries. |

2. 
Data Definition Language(DDL) is a subset of SQL and a part of DBMS(Database Management System). DDL consist of commands like CREATE, ALTER, TRUNCATE and DROP. These commands are used to create or modify the tables in SQL.  

CREATE :  This command is used to create a new table in SQL. The user has to give information like table name, column names, and their datatypes. Ex-  
CREATE TABLE Faculty  
(  
Id number(2),  
Name varchar(30),  
Branch varchar(10)  
);  

ALTER :  This command is used to add, delete or change columns in the existing table. The user needs to know the existing table name and can do add, delete or modify tasks easily. Ex-  
ALTER TABLE Faculty ADD Phone;  

TRUNCATE :  This command is used to remove all rows from the table, but the structure of the table still exists. Ex-  
TRUNCATE TABLE Faculty;  

DROP :  This command is used to remove an existing table along with its structure from the Database. Ex-  
DROP TABLE Faculty;

3. 
The SQL commands that deals with the manipulation of data present in the database belong to DML or Data Manipulation Language.  

INSERT : This command is used to insert data into a table. Ex-  
INSERT INTO Faculty ('300','RAHUL','CSE','23423');  

UPDATE: This command is used to update existing data within a table. Ex-  
UPDATE Faculty SET NAME = 'RAJ' WHERE Id = 300;  

DELETE : It is used to delete records from a database table. Ex-  
DELETE FROM Faculty WHERE NAME = 'RAJ';

4. 
DQL (Data Query Language) statements are used for performing queries on the data within schema objects. The purpose of the DQL Command is to get some schema relation based on the query passed to it. The querying is done with the help of SELECT statement.  

SELECT: It is used to retrieve data from the database. Ex-  
i.  SELECT * FROM Faculty; (This retreives all the columns from the table.)  
ii. SELECT Name, Branch FROM Faculty; (This retreives only the specified columns from the table.)

5. 
Primary Key:  
A primary key is used to ensure that data in the specific column is unique. A column cannot have NULL values. It is either an existing table column or a column that is specifically generated by the database according to a defined sequence.  

Foreign Key:  
A foreign key is a column or group of columns in a relational database table that provides a link between data in two tables. It is a column (or columns) that references a column (most often the primary key) of another table.

6. 
Steps to connect python with mysql-

import mysql.connector

mydb = mysql.connector.connect(
   host="localhost", user="abc", password="password"
)

mycursor = mydb.cursor()  
mycursor.execute("SHOW DATABASES")  
for x in mycursor:  
    print(x)
    
cursor()-  
The Cursor is used to execute statements to communicate with the MySQL database. It can be used to execute SQL statements, fetch data from the result sets, call procedures. Cursor object can be created using the cursor() method.  

execute()-  
The execute() method accepts a MySQL query as a parameter and executes the given query.

7. 
The order in which the clauses in queries are executed is as follows:

i. FROM/JOIN: The FROM and/or JOIN clauses are executed first to determine the data of interest.  
ii. WHERE: The WHERE clause is executed to filter out records that do not meet the constraints.  
iii. GROUP BY: The GROUP BY clause is executed to group the data based on the values in one or more columns.  
iv. HAVING: The HAVING clause is executed to remove the created grouped records that donâ€™t meet the constraints.  
v. SELECT: The SELECT clause is executed to derive all desired columns and expressions.  
vi. ORDER BY: The ORDER BY clause is executed to sort the derived values in ascending or descending order.  
vii. LIMIT/OFFSET: Finally, the LIMIT and/or OFFSET clauses are executed to keep or skip a specified number of rows.